version: "3"

services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      POSTGRES_DB: gdgc-issatso
    volumes:
      - /home/dev-daly/gdgc-issatso/data:/var/lib/postgresql/data
